import {load,save,stages,normalize,draft,canSend,markSent,beginSend,isDuplicate,qualify,isFollowupDue} from './core.js';
import {prepareCandidate} from './discovery.js';
import {ingestCandidates,summarizeIngestion} from './ingest.js';
import {getSendEndpoint,setSendEndpoint,sendLead} from './transport.js';
import {metrics,toCSV,parseCSV} from './analytics.js';
let leads=load().map(normalize);const $=id=>document.getElementById(id);function persist(){save(leads)}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.add=()=>{const l=normalize({first_name:$('first').value.trim(),last_name:$('last').value.trim(),role:$('role').value.trim(),company:$('company').value.trim(),industry:$('industry').value.trim(),email:$('email').value.trim(),linkedin_url:$('linkedin').value.trim(),source:$('source').value.trim(),permission:$('permission').value,permission_source:$('permissionSource').value.trim(),permission_at:$('permissionAt').value, opted_out:$('permission').value==='NO',opted_out_at:$('permission').value==='NO'?new Date().toISOString():''});if(!l.company)return alert('اكتب اسم الشركة');if(l.permission==='YES'&&!l.permission_source)return alert('حدد مصدر Marketing Permission');if(!l.source)return alert('حدد مصدر الـLead');const candidate=prepareCandidate(l);if(!candidate.discovery_eligible)return alert(`Lead غير مؤهل حاليًا — Discovery Score: ${candidate.discovery_score}/100`);if(leads.find(x=>isDuplicate(x,l)))return alert('Lead مكرر: نفس البريد أو LinkedIn موجود بالفعل');leads.unshift(qualify(candidate));persist();document.querySelectorAll('.form input').forEach(x=>x.value='');$('permission').value='';$('permissionAt').value='';render()};
window.makeDraft=id=>{const i=leads.findIndex(x=>x.id===id);if(i<0)return;leads[i]=draft(leads[i]);persist();render()};
window.qualifyLead=id=>{const i=leads.findIndex(x=>x.id===id);if(i<0)return;leads[i]=qualify(leads[i]);persist();render()};
window.editLead=id=>{const i=leads.findIndex(x=>x.id===id);if(i<0)return;const l=leads[i];const first=prompt('الاسم الأول',l.first_name)||l.first_name;const role=prompt('المنصب',l.role)||l.role;const email=prompt('البريد الإلكتروني',l.email)||l.email;const follow=prompt('تاريخ المتابعة YYYY-MM-DD',l.followup_date)||l.followup_date;const notes=prompt('ملاحظات',l.notes)||l.notes;leads[i]={...l,first_name:first,role,email,followup_date:follow,notes,last_contact:l.last_contact};persist();render()};
window.recordReply=id=>{const i=leads.findIndex(x=>x.id===id);if(i<0)return;const note=prompt('ملاحظات الرد',leads[i].notes||'');if(note===null)return;const now=new Date().toISOString();leads[i]={...leads[i],status:'Replied',last_reply_at:now,last_contact:now,notes:note};persist();render()};
window.setStatus=(id,status)=>{const i=leads.findIndex(x=>x.id===id);if(i<0)return;if(status==='Sent')return alert('الإرسال يتم فقط من زر إرسال المحدد بعد نجاح مزود البريد');if(status==='Replied'&&!leads[i].last_reply_at)leads[i]={...leads[i],status,last_reply_at:new Date().toISOString(),last_contact:new Date().toISOString()};else leads[i]={...leads[i],status};persist();render()};
window.setPermission=id=>{const i=leads.findIndex(x=>x.id===id);if(i<0)return;const v=prompt('Marketing Permission: اكتب YES أو NO',''+(leads[i].permission||''));if(v===null)return;const p=v.trim().toUpperCase();if(!['YES','NO'].includes(p))return alert('القيمة يجب أن تكون YES أو NO');const source=prompt('مصدر الإذن/الموافقة',leads[i].permission_source||'');if(source===null)return;const now=new Date().toISOString();leads[i]={...leads[i],permission:p,permission_source:source.trim(),permission_at:now,opted_out:p==='NO',opted_out_at:p==='NO'?now:'',status:p==='NO'&&leads[i].status==='Email Ready'?'Qualified':leads[i].status};persist();render()};
window.setEndpoint=()=>{const v=prompt('رابط Web App للإرسال (Google Apps Script)',getSendEndpoint());if(v===null)return;setSendEndpoint(v);alert(v.trim()?'تم حفظ رابط الإرسال':'تم مسح رابط الإرسال')};
window.sendSelected=async()=>{const ids=[...document.querySelectorAll('.lead-check:checked')].map(x=>x.value);if(!ids.length)return alert('حدد Leads للإرسال');if(ids.length>5)return alert('الحد الأقصى 5 Leads في الدفعة');const selected=ids.map(id=>leads.find(l=>l.id===id)).filter(Boolean);const bad=selected.filter(l=>!canSend(l));if(bad.length)return alert('كل Lead يجب أن يحتوي بريدًا + Permission = YES + Email Ready + بدون Opt-out ولم يسبق إرساله');if(!getSendEndpoint())return alert('أعد إعداد رابط Web App للإرسال أولًا');if(!confirm(`تأكيد إرسال ${selected.length} رسائل؟`))return;let ok=0,errors=[];for(const original of selected){const i=leads.findIndex(x=>x.id===original.id);try{leads[i]=beginSend(leads[i]);persist();const data=await sendLead(leads[i]);leads[i]=markSent(leads[i],data.message_id);ok++}catch(e){leads[i]={...leads[i],send_lock:false};errors.push(`${original.company}: ${e.message}`)}}persist();render();alert(`تم الإرسال: ${ok}/${selected.length}${errors.length?'\n\nأخطاء:\n'+errors.join('\n'):''}`)};
window.removeLead=id=>{if(confirm('حذف Lead؟')){leads=leads.filter(x=>x.id!==id);persist();render()}};
window.exportData=()=>download('khyrat-leads.json',JSON.stringify(leads,null,2),'application/json');window.exportCSV=()=>download('khyrat-leads.csv',toCSV(leads),'text/csv;charset=utf-8');window.importData=()=>$('importFile').click();window.importFileChange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x))throw 0;mergeImported(x)}catch(_){alert('ملف JSON غير صالح')}};r.readAsText(f)};
window.importCSV=()=>$('importCSVFile').click();window.importCSVChange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{mergeImported(parseCSV(r.result))}catch(_){alert('ملف CSV غير صالح')}};r.readAsText(f)};
function mergeImported(imported){const result=ingestCandidates(imported,leads);if(result.accepted.length){leads=[...result.accepted,...leads];persist();render()}const s=summarizeIngestion(result);alert(`نتيجة الاستيراد\nمقبول: ${s.accepted}\nمكرر: ${s.duplicates}\nمرفوض: ${s.rejected}`)}
window.showDue=()=>{const due=leads.filter(l=>isFollowupDue(l));$('search').value='';$('filter').value='All';$('count').textContent=`${due.length} متابعة مستحقة`;$('list').innerHTML=due.map(l=>`<article class="card"><b>${l.company}</b> — ${l.first_name||''} ${l.last_name||''}<div class="muted">متابعة: ${l.followup_date} | الحالة: ${l.status}</div><div>${l.email||'بدون بريد'}</div><div>${l.notes||''}</div><button onclick="editLead('${l.id}')">تفاصيل / تعديل</button></article>`).join('')||'<p>لا توجد متابعات مستحقة</p>'};
window.showDashboard=()=>{const m=metrics(leads);$('search').value='';$('filter').value='All';$('count').textContent='لوحة المتابعة';$('list').innerHTML=`<article class="card"><h3>Pipeline Dashboard</h3><div class="grid"><div>إجمالي Leads: <b>${m.total}</b></div><div>Qualified: <b>${m.qualified}</b></div><div>Email Ready: <b>${m.emailReady}</b></div><div>Sent: <b>${m.sent}</b></div><div>Replies/Progress: <b>${m.replied}</b></div><div>Opt-out: <b>${m.optedOut}</b></div><div>متابعات مستحقة: <b>${m.due}</b></div></div><hr>${Object.entries(m.byStatus).map(([s,n])=>`<div>${s}: <b>${n}</b></div>`).join('')}</article>`};
window.render=()=>{const q=$('search').value.toLowerCase(),f=$('filter').value;const rows=leads.filter(l=>(f==='All'||l.status===f)&&JSON.stringify(l).toLowerCase().includes(q));const m=metrics(leads);$('count').textContent=`${rows.length} Lead | مستحقة: ${m.due} | Sent: ${m.sent} | Replies: ${m.replied}`;$('list').innerHTML=rows.map(l=>`<article class="card"><label><input class="lead-check" type="checkbox" value="${l.id}" ${canSend(l)?'':'disabled'}> جاهز للإرسال</label><div><b>${l.first_name||''} ${l.last_name||''}</b> — ${l.role||'بدون منصب'}</div><b>${l.company}</b> <span class="muted">${l.industry||''}</span><div>${l.email||'بدون بريد'}</div><div class="muted">${l.status} | Permission: ${l.permission||'—'} | Score: ${l.qualification_score||0}</div>${l.source?`<div class="muted">المصدر: ${l.source}</div>`:''}${l.followup_date?`<div class="muted">متابعة: ${l.followup_date}${isFollowupDue(l)?' — مستحقة':''}</div>`:''}${l.last_reply_at?`<div class="muted">آخر رد: ${l.last_reply_at}</div>`:''}${l.notes?`<div>${l.notes}</div>`:''}${l.subject?`<hr><b>${l.subject}</b><pre>${l.body}</pre>`:''}${l.sent_at?`<hr><div class="muted">Sent: ${l.sent_at} | Message ID: ${l.message_id}</div><pre>${l.sent_body||''}</pre>`:''}<div class="grid"><button onclick="qualifyLead('${l.id}')">تأهيل</button><button onclick="makeDraft('${l.id}')">Generate Draft</button><button onclick="recordReply('${l.id}')">تسجيل رد</button><button onclick="editLead('${l.id}')">تفاصيل / تعديل</button><button onclick="setPermission('${l.id}')">Permission</button><select onchange="setStatus('${l.id}',this.value)">${stages.map(s=>`<option ${s===l.status?'selected':''}>${s}</option>`).join('')}</select><button onclick="removeLead('${l.id}')">Delete</button></div></article>`).join('')||'<p>لا توجد Leads</p>'};
$('search').oninput=render;$('filter').onchange=render;$('importFile').onchange=importFileChange;$('importCSVFile').onchange=importCSVChange;render();if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
