import {load,save,stages,normalize,draft,canSend,markSent} from './core.js';
let leads=load().map(normalize);const $=id=>document.getElementById(id);function persist(){save(leads)}
window.add=()=>{const l=normalize({first_name:$('first').value.trim(),last_name:$('last').value.trim(),role:$('role').value.trim(),company:$('company').value.trim(),industry:$('industry').value.trim(),email:$('email').value.trim(),linkedin_url:$('linkedin').value.trim(),permission:$('permission').value});if(!l.company)return alert('اكتب اسم الشركة');leads.unshift(l);persist();document.querySelectorAll('.form input').forEach(x=>x.value='');$('permission').value='';render()};
window.makeDraft=id=>{const i=leads.findIndex(x=>x.id===id);if(i<0)return;leads[i]=draft(leads[i]);persist();render()};
window.setStatus=(id,status)=>{const i=leads.findIndex(x=>x.id===id);if(i<0)return;if(status==='Sent'){if(!canSend(leads[i]))return alert('لا يمكن الإرسال: البريد + موافقة التسويق YES + Email Ready مطلوبة');leads[i]=markSent(leads[i])}else leads[i]={...leads[i],status};persist();render()};
window.removeLead=id=>{if(confirm('حذف Lead؟')){leads=leads.filter(x=>x.id!==id);persist();render()}};
window.exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(leads,null,2)],{type:'application/json'}));a.download='khyrat-leads.json';a.click();URL.revokeObjectURL(a.href)};
window.importData=()=>$('importFile').click();window.importFileChange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x))throw 0;leads=x.map(normalize);persist();render()}catch(_){alert('ملف غير صالح')}};r.readAsText(f)};
window.render=()=>{const q=$('search').value.toLowerCase(),f=$('filter').value;const rows=leads.filter(l=>(f==='All'||l.status===f)&&JSON.stringify(l).toLowerCase().includes(q));$('count').textContent=`${rows.length} Lead`;$('list').innerHTML=rows.map(l=>`<article class="card"><div><b>${l.first_name||''} ${l.last_name||''}</b> — ${l.role||'بدون منصب'}</div><b>${l.company}</b> <span class="muted">${l.industry||''}</span><div>${l.email||'بدون بريد'}</div><div class="muted">${l.status} | Permission: ${l.permission||'—'}</div>${l.subject?`<hr><b>${l.subject}</b><pre>${l.body}</pre>`:''}<div class="grid"><button onclick="makeDraft('${l.id}')">Generate Draft</button><select onchange="setStatus('${l.id}',this.value)">${stages.map(s=>`<option ${s===l.status?'selected':''}>${s}</option>`).join('')}</select><button onclick="removeLead('${l.id}')">Delete</button></div></article>`).join('')||'<p>لا توجد Leads</p>'};$('search').oninput=render;$('filter').onchange=render;$('importFile').onchange=importFileChange;render();
