const HEADERS=['Lead ID','First Name','Last Name','Role','Company','Industry','Email','LinkedIn URL','Source','Marketing Permission','Status','Subject','Email Body','Sent At','Message ID','Reply Status'];
function onOpen(){SpreadsheetApp.getUi().createMenu('Khyrat Lead Engine').addItem('Setup / Repair Sheet','setup').addItem('Generate Drafts','generateDrafts').addItem('Send Selected','sendSelected').addToUi()}
function setup(){const s=SpreadsheetApp.getActive().getSheetByName('Leads')||SpreadsheetApp.getActive().insertSheet('Leads');if(s.getLastRow()===0)s.appendRow(HEADERS);else s.getRange(1,1,1,HEADERS.length).setValues([HEADERS]);s.setFrozenRows(1);s.autoResizeColumns(1,HEADERS.length);SpreadsheetApp.getUi().alert('Leads sheet is ready')}
function rows(){const s=SpreadsheetApp.getActive().getSheetByName('Leads');if(!s)throw Error('Run Setup first');return {s:s,v:s.getDataRange().getValues()}}
function generateDrafts(){const x=rows(),s=x.s,v=x.v;for(let r=1;r<v.length;r++){if(!v[r][1]||!v[r][6])continue;const first=v[r][1],company=v[r][4],industry=v[r][5],subject=`ملاحظة قانونية سريعة لـ ${company}`;const body=`أستاذ ${first}،\n\nبما إن ${company} بتشتغل في ${industry||'مجال الأعمال'}، فغالبًا مع التوسع بتبدأ تظهر نقاط تعاقدية محتاجة مراجعة قبل ما تتحول لمشكلة. ${industryFocus(industry)}\n\nأنا محمود خيرت، محامي بالاستئناف ومتخصص في العقود والشئون القانونية للشركات. أقدر أراجع عقد محدد أو أعمل تقييم سريع للمشكلة وأوضح المخاطر والتعديلات المقترحة.\n\nلو الموضوع مناسب، ابعتلي العقد أو وصف مختصر للمشكلة ونحدد أنسب مستوى.\n\nمحمود خيرت`;s.getRange(r+1,12,1,2).setValues([[subject,body]]);s.getRange(r+1,11).setValue('Email Ready')}SpreadsheetApp.getUi().alert('Drafts generated')}
function industryFocus(i){const x=String(i||'').toLowerCase();if(/saas|software|tech|تكنولوج/.test(x))return'خصوصًا عقود العملاء والاشتراكات والـNDA وتحديد المسئولية.';if(/fin|bank|payment|فنتك|تمويل|مدفوع/.test(x))return'خصوصًا العقود التشغيلية وتوزيع المسئوليات والالتزامات التنظيمية.';if(/health|medical|healthtech|طب|صحة/.test(x))return'خصوصًا عقود مقدمي الخدمة والمسئولية والبيانات والإجراءات التشغيلية.';if(/commerce|e-?commerce|retail|تجارة|متجر/.test(x))return'خصوصًا عقود الموردين والعملاء وشروط البيع والمسئولية.';return'والأهم إن العقود الأساسية تكون واضحة في الالتزامات والمسئولية وآلية إنهاء النزاع.'}
function sendSelected(){const x=rows(),s=x.s,range=s.getActiveRange();const start=Math.max(2,range.getRow()),end=Math.min(s.getLastRow(),start+range.getNumRows()-1);let sent=0;for(let r=start;r<=end;r++){const row=s.getRange(r,1,1,HEADERS.length).getValues()[0];if(!row[6]||row[9]!=='YES'||row[10]!=='Email Ready'||row[13]||row[14]||sent>=5)continue;const m=sendGmail_(row[6],row[11],row[12]);s.getRange(r,11).setValue('Sent');s.getRange(r,14,1,2).setValues([[new Date(),m.id]]);sent++}SpreadsheetApp.getUi().alert(`Sent: ${sent}`)}
function doPost(e){try{const p=JSON.parse(e.postData.contents||'{}');if(!p.lead_id||!p.email||p.permission!=='YES'||!p.subject||!p.body)throw Error('Invalid or unauthorized request');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const key=Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,`${p.lead_id}|${p.email}|${p.subject}|${p.body}`));const props=PropertiesService.getScriptProperties();if(props.getProperty(`sent_${key}`))throw Error('Duplicate send blocked');const m=sendGmail_(p.email,p.subject,p.body);props.setProperty(`sent_${key}`,m.id);return json_({ok:true,message_id:m.id})}finally{lock.releaseLock()}}catch(err){return json_({ok:false,error:String(err.message||err)})}}
function sendGmail_(to,subject,body){const raw=[`To: ${to}`,`Subject: =?UTF-8?B?${Utilities.base64Encode(subject).replace(/=+$/,'')}?=`,`Content-Type: text/plain; charset=UTF-8`,`MIME-Version: 1.0`,'',body].join('\r\n');return Gmail.Users.Messages.send({raw:Utilities.base64EncodeWebSafe(raw)},'me')}
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
