const INDUSTRY={saas:'البرمجيات والخدمات التقنية',tech:'التقنية',fintech:'التكنولوجيا المالية',health:'الخدمات الطبية',ecommerce:'التجارة الإلكترونية',software:'البرمجيات والخدمات التقنية',medical:'الخدمات الطبية'};
export const stages=['New','Qualified','Email Ready','Sent','Replied','Interested','Meeting','Proposal','Won','Lost'];
export function normalize(l){return {...l,id:l.id||crypto.randomUUID(),status:l.status||'New',permission:String(l.permission||'').toUpperCase(),permission_source:l.permission_source||'',permission_at:l.permission_at||'',opted_out:!!l.opted_out,opted_out_at:l.opted_out_at||'',subject:l.subject||'',body:l.body||'',sent_at:l.sent_at||'',message_id:l.message_id||'',sent_subject:l.sent_subject||'',sent_body:l.sent_body||'',followup_date:l.followup_date||'',notes:l.notes||'',last_contact:l.last_contact||'',last_reply_at:l.last_reply_at||'',source:l.source||'',qualification_score:Number.isFinite(Number(l.qualification_score))?Number(l.qualification_score):0,send_lock:!!l.send_lock,send_key:l.send_key||''}}
export function draft(l){const n=l.first_name||'أستاذ/أستاذة';const focus=INDUSTRY[(l.industry||'').toLowerCase()]||l.industry||'نشاط الشركة';const role=l.role||'فريق الإدارة';return {...l,subject:`ملاحظة قانونية سريعة لـ ${l.company}`,body:`أستاذ ${n}،\n\nبحكم نشاط ${l.company} في ${focus}، ومع نمو الشركة تظهر نقاط تعاقدية تستحق المراجعة قبل أن تتحول لمشكلة.\n\nأنا محمود خيرت، محامي بالاستئناف ومتخصص في العقود والشئون القانونية للشركات. أقدر أراجع عقد محدد أو أقيّم مشكلة قانونية وأوضح المخاطر والتعديلات المقترحة.\n\nلو مناسب، ابعتلي العقد أو وصف مختصر للمشكلة ونحدد أنسب مستوى للخدمة.\n\nمحمود خيرت`,status:'Email Ready',notes:l.notes||`جهة الاتصال: ${role}`}}
export function qualificationScore(l){l=normalize(l);let s=0;const role=String(l.role).toLowerCase();const industry=String(l.industry).toLowerCase();if(l.email)s+=25;if(l.permission==='YES')s+=25;if(/ceo|founder|co[- ]?founder|chief executive|مدير|مؤسس|رئيس مجلس|عضو منتدب/.test(role))s+=25;if(/saas|software|tech|technology|fintech|ecommerce|health|medical|برمج|تقن|تكنولوجيا|تجارة إلكترونية|طبي/.test(industry))s+=15;if(l.linkedin_url)s+=10;return Math.min(100,s)}
export function qualify(l){l=normalize(l);const score=qualificationScore(l);return {...l,qualification_score:score,status:score>=60&&l.status==='New'?'Qualified':l.status}}
export function isFollowupDue(l,today=new Date()){l=normalize(l);if(!l.followup_date||['Won','Lost'].includes(l.status))return false;const d=new Date(`${l.followup_date}T23:59:59`);return !Number.isNaN(d.getTime())&&d.getTime()<=new Date(today).getTime()}
export function canSend(l){l=normalize(l);return !!(l.email&&l.permission==='YES'&&!l.opted_out&&l.status==='Email Ready'&&!l.sent_at&&!l.message_id&&!l.send_lock)}
export function sendKey(l){l=normalize(l);return [l.id,String(l.email).trim().toLowerCase(),l.subject,l.body].join('|')}
export function beginSend(l){l=normalize(l);if(!canSend(l))throw Error('Lead غير مؤهل للإرسال أو سبق إرساله');return {...l,send_lock:true,send_key:sendKey(l)}}
export function markSent(l,message_id=''){if(!message_id)throw Error('Message ID مطلوب');const now=new Date().toISOString();return {...l,status:'Sent',sent_at:now,last_contact:now,message_id,sent_subject:l.subject,sent_body:l.body,send_lock:false,send_key:sendKey(l)}}
export function markSendFailed(l){return {...normalize(l),send_lock:false}}
export function dedupeKey(l){l=normalize(l);return `${String(l.email||'').trim().toLowerCase()}|${String(l.linkedin_url||'').trim().toLowerCase()}`}
export function isDuplicate(a,b){const x=normalize(a),y=normalize(b);return !!((x.email&&y.email&&String(x.email).trim().toLowerCase()===String(y.email).trim().toLowerCase())||(x.linkedin_url&&y.linkedin_url&&String(x.linkedin_url).trim().toLowerCase()===String(y.linkedin_url).trim().toLowerCase()))}
