const SEARCH_ENGINES={google:'https://www.google.com/search?q=',bing:'https://www.bing.com/search?q='};
const BLOCKED_HOSTS=new Set(['google.com','www.google.com','bing.com','www.bing.com','linkedin.com','www.linkedin.com','facebook.com','www.facebook.com','instagram.com','www.instagram.com','youtube.com','www.youtube.com','wikipedia.org','www.wikipedia.org']);
const PUBLIC_PATHS=['/about','/about-us','/team','/our-team','/leadership','/management','/contact','/contact-us','/company','/careers'];
function enc(v){return encodeURIComponent(String(v||''))}
function clean(v=''){return String(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim()}
function decode(v=''){let x=String(v);for(let i=0;i<3;i++){try{const n=decodeURIComponent(x);if(n===x)break;x=n}catch{break}}return x}
export function buildDeepQueries({roles=[],industries=[],country='Egypt',cities=['Cairo','Alexandria'],maxQueries=160}={}){const rs=roles.length?roles:['CEO','Founder','Co-Founder','Owner','Managing Director','General Manager','HR Director','HR Manager','Head of HR','Legal Manager','Legal Director','General Counsel','Procurement Manager','Finance Director','COO','CFO'];const ins=industries.length?industries:['manufacturing','technology','software','fintech','healthcare','medical','construction','trading','logistics','real estate','food','services'];const qs=[];for(const r of rs){for(const i of ins){for(const c of cities){qs.push(`"${r}" "${i}" "${c}" "Egypt"`);qs.push(`site:linkedin.com/in/ "${r}" "${i}" "${c}"`);if(qs.length>=maxQueries)return qs}}}return qs}
export function buildCompanyQueries({company,country='Egypt'}={}){const c=String(company||'').trim();return [`"${c}" "Egypt"`, `"${c}" contact`, `"${c}" email`, `"${c}" management`, `"${c}" CEO`, `"${c}" HR`, `"${c}" legal`, `"${c}" procurement`, `"${c}" site:linkedin.com/in/`].map(q=>q.trim()).filter(Boolean)}
export function searchUrl(query,{engine='google'}={}){return `${SEARCH_ENGINES[engine]||SEARCH_ENGINES.google}${enc(query)}`}
export function extractPublicDomains(html=''){const out=[];const seen=new Set();const re=/<a\b[^>]*href=["']([^"']+)["']/gi;let m;while((m=re.exec(String(html)))){let href=decode(m[1]).replace(/&amp;/g,'&');const q=href.match(/[?&](?:q|url)=([^&]+)/i);if(q)href=decode(q[1]);try{const u=new URL(href);const host=u.hostname.toLowerCase().replace(/^www\./,'');if(!/^https?:$/.test(u.protocol)||BLOCKED_HOSTS.has(host)||seen.has(host)||host.includes('googleusercontent'))continue;seen.add(host);out.push({domain:host,url:`${u.protocol}//${u.hostname}`})}catch{}}return out}
export function extractBusinessSignals(html='',sourceUrl=''){const text=clean(html);const emails=[...new Set((text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[]).map(x=>x.toLowerCase()).filter(e=>!/(example|wix|sentry|schema|noreply|no-reply)/.test(e)))];const phones=[...new Set(text.match(/(?:\+?20|0)\s*1[0125]\s*[0-9\s-]{7,12}/g)||[])];const people=[];for(const m of text.matchAll(/\b([A-Z][a-z]{2,20}(?:\s+[A-Z][a-z]{2,20}){1,3})\b[^.]{0,80}\b(CEO|Founder|Co-Founder|Managing Director|General Manager|HR Director|HR Manager|Head of HR|Legal Manager|Legal Director|General Counsel|Procurement Manager|COO|CFO)\b/gi)){people.push({name:m[1].trim(),role:m[2].trim(),source_url:sourceUrl})}return {emails,phones,people:people.slice(0,30),source_url:sourceUrl}}
export async function deepGoogleDiscover({queries=buildDeepQueries(),engine='google',fetchImpl=globalThis.fetch,timeoutMs=15000,maxDomains=300,maxPeople=500}={}){if(typeof fetchImpl!=='function')throw Error('Fetch غير متاح');const domains=new Map(),people=new Map();for(const query of queries){for(const eng of engine==='google'?['google','bing']:[engine]){try{const r=await fetchImpl(searchUrl(query,{engine:eng}),{headers:{'User-Agent':'Mozilla/5.0 Chrome/128 Safari/537.36','Accept':'text/html,application/xhtml+xml','Accept-Language':'en-US,en;q=0.8,ar;q=0.6'},signal:AbortSignal.timeout(timeoutMs)});if(!r.ok)continue;const html=await r.text();for(const d of extractPublicDomains(html)){if(!domains.has(d.domain))domains.set(d.domain,{...d,queries:[query],source_confidence:'medium'});else domains.get(d.domain).queries.push(query)}const signals=extractBusinessSignals(html,searchUrl(query,{engine:eng}));for(const p of signals.people){const k=`${p.name.toLowerCase()}|${p.role.toLowerCase()}`;if(!people.has(k))people.set(k,{...p,query,engine:eng,source:'google_public_search',source_confidence:'medium'})}if(domains.size>=maxDomains&&people.size>=maxPeople)break}catch{}}if(domains.size>=maxDomains&&people.size>=maxPeople)break;await new Promise(r=>setTimeout(r,300))}return {domains:[...domains.values()].slice(0,maxDomains),people:[...people.values()].slice(0,maxPeople),queries:queries.length,engine:'google+bingsafe-fallback'} }
export async function crawlPublicCompany({baseUrl,fetchImpl=globalThis.fetch,timeoutMs=12000,maxPages=8}={}){const root=new URL(baseUrl);const queue=[root.href];const seen=new Set(),signals={emails:[],phones:[],people:[],pages:[]};while(queue.length&&seen.size<maxPages){const url=queue.shift();if(seen.has(url))continue;seen.add(url);try{const r=await fetchImpl(url,{headers:{'User-Agent':'Mozilla/5.0 Chrome/128 Safari/537.36','Accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(timeoutMs)});if(!r.ok)continue;const html=await r.text();const s=extractBusinessSignals(html,url);signals.emails.push(...s.emails);signals.phones.push(...s.phones);signals.people.push(...s.people);signals.pages.push(url);const re=/<a\b[^>]*href=["']([^"']+)["']/gi;let m;while((m=re.exec(html))){try{const u=new URL(decode(m[1]),url);if(u.hostname===root.hostname&&PUBLIC_PATHS.some(p=>u.pathname.toLowerCase().startsWith(p))&&!seen.has(u.href))queue.push(u.href)}catch{}}}catch{}}return {...signals,emails:[...new Set(signals.emails)],phones:[...new Set(signals.phones)],people:[...new Map(signals.people.map(p=>[`${p.name}|${p.role}|${p.source_url}`,p])).values()].slice(0,50)} }
export const deepDiscoveryRules={publicWebOnly:true,noLinkedInLogin:true,noControlBypass:true,noPrivateContactDiscovery:true,noAutomatedOutreach:true,blockedHosts:[...BLOCKED_HOSTS],publicPaths:PUBLIC_PATHS};
