const SNAPSHOT_URL='https://raw.githubusercontent.com/mr-romel/linkedin-scraper/main/artifacts/linkedin-decision-makers.json';
const CSV_URL='https://raw.githubusercontent.com/mr-romel/linkedin-scraper/main/artifacts/linkedin-decision-makers.csv';
const $=id=>document.getElementById(id);
function esc(v=''){return String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
async function fetchLeads(){const r=await fetch(`${SNAPSHOT_URL}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`تعذر تحميل قائمة LinkedIn (${r.status})`);const d=await r.json();if(!Array.isArray(d.leads))throw Error('ملف LinkedIn غير صالح');return d}
function render(data){const host=$('linkedinDiscoveryPanel');if(!host)return;const leads=data.leads||[];const high=leads.filter(x=>(x.qualification_score||0)>=75).length;host.innerHTML=`<h3>LinkedIn — صناع القرار</h3><div class="muted">آخر تشغيل: ${esc(data.generated_at||'غير متاح')} | النتائج: ${leads.length} | أولوية عالية: ${high}</div><div class="grid"><button id="refreshLinkedin">تحديث القائمة</button><a id="downloadLinkedin" href="${CSV_URL}" target="_blank" rel="noopener" style="display:block;text-align:center;padding:10px;margin:5px 0;border:1px solid #bbb;border-radius:8px;text-decoration:none;color:inherit">فتح CSV</a></div><input id="linkedinSearch" placeholder="بحث بالاسم أو الشركة أو المنصب"><div id="linkedinRows" class="card" style="max-height:420px;overflow:auto"></div>`;const paint=()=>{const q=String($('linkedinSearch')?.value||'').toLowerCase();const rows=leads.filter(x=>`${x.name} ${x.company} ${x.role} ${x.industry}`.toLowerCase().includes(q)).slice(0,100);$('linkedinRows').innerHTML=rows.map((r,i)=>`<div style="padding:9px 0;border-bottom:1px solid #eee"><b>${i+1}. ${esc(r.name||r.title||'اسم غير متاح')}</b><div>${esc(r.role||'')} — ${esc(r.company||'')}</div><div class="muted">${esc(r.industry||'')} | قرار: ${esc(r.decision_power||'')} (${r.decision_power_score||0}) | Qualification: ${r.qualification_score||0}</div><div class="muted">احتياج محتمل: ${esc((r.legal_needs||[]).join('، '))}</div><a href="${esc(r.linkedin_url||'#')}" target="_blank" rel="noopener">فتح LinkedIn</a></div>`).join('')||'لا توجد نتائج مطابقة'};$('linkedinSearch').oninput=paint;$('refreshLinkedin').onclick=refresh;paint()}
async function refresh(){const host=$('linkedinDiscoveryPanel');if(host)host.innerHTML='<h3>LinkedIn — صناع القرار</h3><div class="muted">جاري تحميل أحدث قائمة...</div>';try{render(await fetchLeads())}catch(e){if(host)host.innerHTML=`<h3>LinkedIn — صناع القرار</h3><div class="muted">${esc(e.message)}</div>`}}
function init(){if($('linkedinDiscoveryPanel'))return;const panel=document.createElement('section');panel.id='linkedinDiscoveryPanel';panel.className='card';document.querySelector('main').insertBefore(panel,document.querySelector('#list'));refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
