import test from 'node:test';
import assert from 'node:assert/strict';
import {normalize,draft,canSend,markSent,sendKey,beginSend,markSendFailed,isDuplicate,qualificationScore,qualify,isFollowupDue} from '../core.js';

test('draft makes a lead email-ready',()=>{const l=draft(normalize({company:'Acme',first_name:'علي',industry:'saas',email:'a@x.com',permission:'YES'}));assert.equal(l.status,'Email Ready');assert.match(l.subject,/Acme/);assert.match(l.body,/علي/)})
test('send gate requires permission, opt-out block, and blocks sent leads',()=>{const base=normalize({company:'Acme',email:'a@x.com',permission:'YES',status:'Email Ready',subject:'s',body:'b'});assert.equal(canSend(base),true);assert.equal(canSend({...base,opted_out:true}),false);const sent=markSent(base,'msg-1');assert.equal(canSend(sent),false);assert.equal(sent.message_id,'msg-1');assert.equal(sent.sent_subject,'s');assert.equal(sent.sent_body,'b')})
test('send lock prevents concurrent duplicate sends',()=>{const base=normalize({id:'1',email:'a@x.com',permission:'YES',status:'Email Ready',subject:'s',body:'b'});const locked=beginSend(base);assert.equal(locked.send_lock,true);assert.equal(canSend(locked),false);assert.throws(()=>beginSend(locked));assert.equal(markSendFailed(locked).send_lock,false)})
test('send key is deterministic',()=>{const l=normalize({id:'1',email:'a@x.com',subject:'s',body:'b'});assert.equal(sendKey(l),sendKey({...l}))})
test('dedupe is case-insensitive for email and linkedin',()=>{assert.equal(isDuplicate({email:'A@X.COM'},{email:'a@x.com'}),true);assert.equal(isDuplicate({linkedin_url:'https://linkedin.com/in/test'},{linkedin_url:'https://linkedin.com/in/test'}),true);assert.equal(isDuplicate({email:'a@x.com'},{email:'b@x.com'}),false)})
test('qualification scores useful B2B leads and qualifies strong leads',()=>{const l=normalize({company:'Tech Co',email:'a@x.com',permission:'YES',role:'CEO',industry:'saas',linkedin_url:'https://linkedin.com/in/a'});assert.equal(qualificationScore(l),100);assert.equal(qualify(l).status,'Qualified');const n=normalize({company:'Other',email:'a@x.com',permission:'YES',role:'CEO',industry:'saas'});assert.equal(qualify(n).status,'Qualified')})
test('follow-up is due on or before date and excludes won/lost',()=>{assert.equal(isFollowupDue({followup_date:'2026-09-10',status:'Sent'},new Date('2026-09-11T12:00:00Z')),true);assert.equal(isFollowupDue({followup_date:'2026-09-12',status:'Sent'},new Date('2026-09-11T12:00:00Z')),false);assert.equal(isFollowupDue({followup_date:'2026-09-10',status:'Won'},new Date('2026-09-11T12:00:00Z')),false)})
